Dialog:modify() support for combobox options
aseprite/aseprite pull request #3036
Opened 2021-11-02 04:04 UTC by Omar-Abdul-Aziz

`Dialog:modify()` now supports modifying
1. both `options` and `option` which sets `options` then selects the item specified with `option`
2. `options` alone which sets the selected item to the first item in the list or sets text to `""` for empty combobox
3. `option` alone which is already supported

2021-11-02 11:26 UTC, Omar-Abdul-Aziz commented
one thing I'm curious about... can/should I pull to `beta` branch? or would changes in `main` be pushed to `beta`?

2021-11-02 11:29 UTC, dacap commented
Hi @Omar-Abdul-Aziz, I'll try to look to your PR ASAP, for API changes (mainly new functions) we can use the `main` branch 👍

2021-11-15 15:28 UTC, Omar-Abdul-Aziz commented
@dacap Just wanna make sure at least the workflow is approved so this PR doesn't get automatically deleted after 30 days of creation

> Workflow runs that have been awaiting approval for more than 30 days are automatically deleted.

2021-11-16 11:55 UTC, dacap requested changes
Thanks @Omar-Abdul-Aziz for your PR and to implement this. There are some minor changes to made. Also please keep the default text of the PR:

```
I agree that my contributions are licensed under the Individual Contributor License Agreement V3.0 ("CLA") as stated in https://github.com/aseprite/sourcecode/blob/main/cla.md

I have signed the CLA following the steps given in https://github.com/aseprite/sourcecode/blob/main/sign-cla.md#sign-the-cla
```

2021-11-16 11:55 UTC, dacap commented on src/app/script/dialog_class.cpp
> +          combobox->getEntryWidget()->setText("");
It looks like we need an extra indentation level here:
```suggestion
          lua_pushnil(L);
          bool empty = true;
          while (lua_next(L, -2) != 0) {
            if (auto p = lua_tostring(L, -1)){
              combobox->addItem(p);
              empty = false;
            }
            lua_pop(L, 1);
          }
          if (empty)
            combobox->getEntryWidget()->setText("");
```

2021-11-24 21:33 UTC, Omar-Abdul-Aziz commented
sorry for annoyance but there's a week left until this gets automatically deleted @dacap

2021-11-30 21:49 UTC, dacap commented
@Omar-Abdul-Aziz PRs are not automatically closed or deleted in this repository, anyway I'll try to merge this change today 👍

2021-11-30 22:02 UTC, dacap commented
Merged in a squashed commit (with minor style changes): https://github.com/aseprite/aseprite/commit/b30e64648e89319f12b688d34fd3263e89cc177b

I don't like that changing the `options` with the same options will reset the selected `option`, but it can be something to be done/fixed in a future.

2021-11-30 22:02 UTC, closed without merging

2021-11-30 22:02 UTC, dacap commented
Forgot to say thanks for this patch @Omar-Abdul-Aziz, it will be released in v1.2.31 👍