Silent savefile
aseprite/aseprite pull request #3216
Opened 2022-03-20 12:56 UTC by VelocityRa

My use case for these two changes is improving the "Automatic Snapshot" feature here [https://sprngr.itch.io/aseprite-record](https://t.co/qGqx88tG9A) for recording timelapses.

Wasn't sure if I should make `sprite:saveAs`/`saveCopyAs` have named params instead since that would break the API afaik. Instead I exposed the 'add to recent files' param as an optional second bool. The other one (whether to display the alert) is set to always not display (when called via scripting).

---

I tried to contact maintainers on `#aseprite-dev` on Discord and Twitter so as to ask for feedback and not waste my time with a pre-emptive PR but received no response.

---

I agree that my contributions are licensed under the Individual Contributor License Agreement V3.0 ("CLA") as stated in https://github.com/aseprite/sourcecode/blob/main/cla.md

I have signed the CLA following the steps given in https://github.com/aseprite/sourcecode/blob/main/sign-cla.md#sign-the-cla

2022-03-29 19:45 UTC, VelocityRa commented
Bump?
It's been 9 days...

2022-03-29 22:42 UTC, VelocityRa commented
Everything about how the repo is set up (detailed building instructions, nice code/tree documentation, etc) suggests that you actually _want_ people contributing.

Not to mention that you require contributors to give you their _home address_ for the privilege of being able to contribute (talking about the CLA thing). And then you ignore their PRs.

2022-03-29 22:47 UTC, VelocityRa commented
I don't intend to be rude; hopefully you understand my frustration.

2022-03-30 00:48 UTC, dacap commented
Hi @VelocityRa, sorry but sometimes priorities are focused in other things and I cannot review the PRs. I know that in a perfect world PRs will be reviewed immediately and merged if everything is fine. I also know that there are a lot of old PRs. But my time is limited and I'm already giving too much of my personal life in this project.

2022-03-30 02:01 UTC, dacap commented
I have just added some information about the current CLA process https://github.com/aseprite/sourcecode/issues/83

I'll review this PR just right now and merge it, as it LGTM

2022-03-30 02:32 UTC, dacap requested changes
Some minor changes requested to keep the default behavior (addToRecent) when the parameter is not specified.

2022-03-30 02:32 UTC, dacap commented on src/app/commands/cmd_save_file.cpp
> +  m_addToRecentFiles = (addToRecentFiles == "true");
I think I would prefer a shorter param name like "addToRecent", and check if it's empty (in that case we add to recent, as it's the default behavior):
```suggestion
  const std::string addToRecent = params.get("addToRecent");
  m_addToRecent = (addToRecent.empty() || (addToRecent == "true"));
```
In a future we have to change the parameters of all commands to NewParams, but that is a refactor for the future.

2022-03-30 02:32 UTC, dacap commented on src/app/script/sprite_class.cpp
> +      params.set("addToRecentFiles", lua_toboolean(L, -1) ? "true" : "false");
```suggestion
      params.set("addToRecent", lua_toboolean(L, -1) ? "true" : "false");
```

2022-03-30 02:36 UTC, dacap commented
Oh sorry, didn't check the comment about the new parameter in the Lua API. I would prefer named parameters in this case (as we don't know what the boolean means from the client-side).

Basically we should be able to call Sprite:saveAs(string) or Sprite:saveAs{table} ([app.alert](https://github.com/aseprite/api/blob/main/api/app.md#appalert) does something similar)

2024-05-10 18:48 UTC, dacap commented
This was implemented with 0cc1161d6494bdb0f06b6a3c470055ec5f952939 and 3ea0437e1dd92b939ff103e5e775397f345cfa52

2024-05-10 18:48 UTC, closed without merging