Add other color comparison criteria to findBestfit
aseprite/aseprite pull request #3395
Opened 2022-06-24 20:15 UTC by Gasparoken

Implementation of item 1 of https://github.com/aseprite/aseprite/issues/3394

2022-06-28 22:05 UTC, dacap requested changes

2022-06-28 22:05 UTC, dacap commented on src/doc/palette.cpp
> +double f(double t)
Add static keyword:
```suggestion
static double f(double t)
```

2022-06-28 22:05 UTC, dacap commented on src/doc/palette.cpp
> +    return pow(t, 0.3333333333333333);
Use `std::` namespace for standard functions. And include `<cmath>`:
```suggestion
    return std::pow(t, 0.3333333333333333);
```

2022-06-28 22:05 UTC, dacap commented on src/doc/palette.cpp
> +void rgbToOtherSpace(double& r, double& g, double& b, FitCriteria fc)
```suggestion
static void rgbToOtherSpace(double& r, double& g, double& b, FitCriteria fc)
```

2022-06-28 22:05 UTC, dacap commented on src/doc/palette.cpp
> +  if (fc == linearizedRGB) {
I think we can use a switch-case here:
```suggestion
  switch (fc) {
    case FitCriteria::linearizedRGB:
      ...
      break;
  }  
```

2022-06-28 22:05 UTC, dacap commented on src/doc/palette.cpp
> +enum FitCriteria{
Prefer a `enum class` for global enums (enums outside classes):
```suggestion
enum class FitCriteria {
```

2022-06-28 22:05 UTC, dacap commented on src/doc/palette.h
> +    int findBestfit3(int r, int g, int b, int a, int mask_index) const;
Do we need findBestfit()? Or can we just change the implementation of findBestfit() directly with the new findBest3 code?

2022-07-05 12:37 UTC, Gasparoken commented
Changes just pushed.

2022-07-14 17:10 UTC, dacap commented
Cherry-picked https://github.com/aseprite/aseprite/commit/54443ad20d0f0c018704d5f201ca34d39443d61e

2022-07-14 17:10 UTC, closed without merging