Fix [regression] textBox not rendering text (doesn't update the bounds area of the text box)
aseprite/aseprite pull request #3441
Opened 2022-07-27 12:37 UTC by Gasparoken

Regression in dd0c29620974e56d9e62653804b996740a89e88a (Use tooltip_text style & color to paint tooltip windows #2554).
Prior this fix, text box do not update its bounds area because it has not a style assigned.

2022-07-27 14:01 UTC, martincapello approved these changes
Looks good to me! Just tested this fix and it seem to work just fine.

2022-07-27 17:19 UTC, dacap requested changes
Please use lower case for ids as all other styles: `textbox_text`

2022-07-27 17:45 UTC, Gasparoken commented
Thank you @dacap.  Done.

2022-07-28 18:16 UTC, Gasparoken commented
This PR will solve issue #3442

2022-07-29 00:31 UTC, brickviking commented
I tried the suggested fix for this over in the beta branch too, it seems that aseprite/data/extensions/aseprite-theme/dark/theme.xml is also affected. I'm guessing the same lines can go in.

2022-07-29 21:52 UTC, Gasparoken commented
The last forced push also resolves the incorrect wrapped text in the Console.

2022-07-29 21:56 UTC, Gasparoken commented
Hi @brickviking. I've tried other themes (without 'textbox_text' style lines on 'theme.xml') and can't reproduce the original error. The Beta branch will be updated eventually.

2022-07-30 00:00 UTC, brickviking commented
Yup, agreed. When I ran Help->About with dark theme enabled, I got the text, though it was white background, dark foreground, presumably because it hadn't been assigned with `<background color="textbox_face" />` and `<text color="textbox_text" align="left" />`. Once I put in the requisite lines, the text appeared the right colours for the theme.

2022-08-02 19:50 UTC, dacap commented
Thanks everybody! Merged in https://github.com/aseprite/aseprite/commit/55885ee266fbb7d01894cf0a456aaceb8cc807c7 and then in beta in https://github.com/aseprite/aseprite/commit/05bf34f084b6f372a2cab2d38204192085840923 (adding the new style to the dark xml to avoid a white console) :+1:

2022-08-02 19:51 UTC, closed without merging