Fix gif opening causes color reindexing when duplicate colors in color table (fix #3426)
aseprite/aseprite pull request #3446
Opened 2022-07-28 23:06 UTC by Gasparoken

2022-07-28 23:13 UTC, Gasparoken commented
Passed standard tests, also tested with our gif database. Improved similarity between GIFs loaded/saved in Aseprite.

2022-08-02 02:07 UTC, dacap commented on src/app/file/gif_format.cpp
> +                   localCMap->Colors[i].Blue, 256) == palette->getEntry(i)) {
Didn't test this yet, but seeing the code, it looks like this 256 should be 255.
```suggestion
                   localCMap->Colors[i].Blue, 255) == palette->getEntry(i)) {
```

2022-08-02 02:40 UTC, dacap commented
Just in case, the issue was reported for main, and this patch is for beta. Anyway I would prefer to apply this only in beta (as it will be the new decoder/encoder anyway).

2022-08-02 11:19 UTC, Gasparoken commented
Thank you David for the review.

> Just in case, the issue was reported for main, and this patch is for beta. Anyway I would prefer to apply this only in beta (as it will be the new decoder/encoder anyway).

You are right, and this is not casual. I did it in beta since many important modifications of the gif format were made in this branch in the last years.

2022-08-08 20:36 UTC, dacap requested changes
Just in case, the 256 is still there (in both places), not sure if this PR is ready to be merged.

2022-08-09 14:22 UTC, Gasparoken commented
Sorry for that. Idk why 256 is still there. I remember changing the value🤔. Perhaps a mix-up from working with VSCODE and XCODE at the same time (I'm guessing I may have been open to the same file and hit 'save' on a previous view of the file, Idk). I'll fix it soon.

2022-08-10 21:07 UTC, Gasparoken commented
Done.

2022-09-16 18:06 UTC, martincapello approved these changes
Looks good to me!

2022-09-20 16:59 UTC, dacap commented
I'll merge this PR :+1: 

Anyway I've detected other issue but I think it's unrelated to this.

2022-09-20 17:21 UTC, dacap commented
Just merged https://github.com/aseprite/aseprite/commit/fbf62407d3c0a719a531f0a61c22d0a443a981a3 and created other issue related to the gif encoder (but unrelated to this patch)

2022-09-20 17:21 UTC, closed without merging