Fix windows bounds when modifiying properties inside canvas onpaint handler (fix #3747)
aseprite/aseprite pull request #3759
Opened 2023-03-17 18:13 UTC by martincapello

Fix #3747

2023-03-20 14:08 UTC, dacap commented
It looks like this fix bring back the problems solved in 06a387fd45f288c69213a5cc0b09fdbf742dfdde

2023-03-23 11:45 UTC, martincapello commented
I almost give up on this one... 😅

2023-03-23 12:20 UTC, dacap requested changes

2023-03-23 12:41 UTC, martincapello commented on src/app/script/dialog_class.cpp
>    }
But actually that is not the problem...
 
Original code:
```c++
    type = lua_getfield(L, 2, "hexpand");
    type = lua_getfield(L, 2, "vexpand");
    if (type != LUA_TNIL) hexpand = lua_toboolean(L, -2);
    if (type != LUA_TNIL) vexpand = lua_toboolean(L, -1);
    lua_pop(L, 2);
```
See how type is assigned twice, the first assignation is lost before having a chance to use it in the if condition.

2023-03-23 12:48 UTC, dacap commented on src/app/script/dialog_class.cpp
>    }
Oh yes :+1: it's ok

2023-03-23 13:04 UTC, martincapello commented on src/app/script/dialog_class.cpp
> +  bool m_paintingCanvas;
Oh, I actually didn't realize it was a struct. Thanks, will update this!

2023-03-23 13:20 UTC, martincapello commented on src/app/script/dialog_class.cpp
> +                           std::function<void()> afterLuaCall = nullptr)
That's clever...I need to improve my templating-fu. Thanks!

2023-03-23 14:42 UTC, martincapello commented
What about now? It is simpler, but not sure if we should check in layout and expandWindow methods

2023-03-23 18:26 UTC, dacap commented
It looks like this can broke some other cases, e.g.:

```lua
local dialog = Dialog("Canvas Resize Test")
dialog
:canvas{
    width = 200,
    height = 200,
    onpaint = function(ev)
      local context = ev.context
        dialog 
        :modify{id = "canvas-width", text = tostring(context.width)} 
        :modify{id = "canvas-height", text = tostring(context.height)}
    end
}
:label{id = "canvas-width", label = "Width:"}
:label{id = "canvas-height", label = "Height:"}
:button{id = "resize", text = "Resize", onclick=function()
	  local rc = dialog.bounds
	  rc.width = rc.width + 10
	  dialog.bounds = rc
       end}
dialog:show{wait = false}
```

The new "Resize" button works in the current version making the window bigger, but not with this fix.

2023-03-27 17:39 UTC, martincapello commented
I'm not sure what or how it happened, but today when I tried the latest approach in Linux it didn't even work, I mean, the bug wasn't fixed. So I tested again in macOS...same, the bug was still there, the dialog's height wasn't updated...so...I'm shocked how it seemed to me that it worked last Friday...
I'm going to push a slight change to make it work (I've tested it in Ubuntu 18.04.6 LTS and macOS).

2023-03-27 20:23 UTC, martincapello commented
Seems that the issue is not related to this fix as far as I was able to debug in linux. Seems that the problem is because when we ask for the window's size the message that resized the window didn't arrive yet, so we got the size before resize, then the window size is set to its previous size. To clarify, this is the order of messages:
1. Set new window size
2. Get window size (here we get the old size because the message sent in 1 wasn't processed yet)
3. Set window size using the size of previous step (the window is set again to its original size)

This also explains why you can see a flickering effect in the window's width.

To fix this I've created https://github.com/aseprite/laf/pull/59

2023-03-28 17:43 UTC, closed without merging

2023-03-29 12:34 UTC, dacap commented
The commit missed (fix #3747), closing the issue manually.