Replace ColorEntry with ExprEntry in Color Sliders
aseprite/aseprite pull request #3930
Opened 2023-06-21 23:44 UTC by Akylzhan

Adds https://github.com/aseprite/aseprite/issues/3900

I agree that my contributions are licensed under the Individual Contributor License Agreement V4.0 ("CLA") as stated in https://github.com/igarastudio/cla/blob/main/cla.md

I have signed the CLA following the steps given in https://github.com/igarastudio/cla#signing

2023-06-22 22:15 UTC, dacap requested changes
Hi @Akylzhan, thanks for your PR. Probably we require a different approach for this. Probably just changing:

```c++
class ColorEntry : public ExprEntry
```

2023-06-22 22:15 UTC, dacap commented on src/app/ui/color_sliders.cpp
> +  item.entry     = new ExprEntry();
With this change we lost the behavior of `ColorEntry` (we cannot use up/down arrow keys to modify the value).

2023-06-22 22:15 UTC, dacap commented on src/app/ui/color_sliders.h
> +      app::ExprEntry* entry = nullptr;
This change is not required.

2023-06-22 22:39 UTC, Akylzhan commented
@dacap Yes, you are right. Did not think about that. Changed ColorEntry's base to ExprEntry

2023-06-23 16:11 UTC, dacap commented
Thanks @Akylzhan, I've just merged this change in https://github.com/aseprite/aseprite/commit/3e171d0f6aebeff50138bce6fb98c987d1006723 with a missing setText("0") so the entry fields start with 0 in the *Edit > Adjustments > Hue/Saturation* dialog.

2023-06-23 16:11 UTC, closed without merging