Add check box "Same in all tools" in the Dynamics options window (fix #4003)
aseprite/aseprite pull request #4006
Opened 2023-08-16 21:45 UTC by Gasparoken

Now each tool has independent 'dynamic options'. A global configuration for all tools is also possible via the 'Same in all tools' option.

fix #4003

2023-08-17 17:56 UTC, martincapello approved these changes

2023-08-17 22:03 UTC, dacap requested changes

2023-08-17 22:03 UTC, dacap commented on src/app/ui/dynamics_popup.cpp
> +    auto& dynaPref = pref->tool(App::instance()->activeTool()).dynamics;
No need to pass the singleton Preferences instance as argument:
```suggestion
void DynamicsPopup::loadDynamicsPref()
{
  auto& dynaPref = Preferences::instance().tool(App::instance()->activeTool()).dynamics;
```

2023-08-17 22:03 UTC, dacap commented on src/app/ui/dynamics_popup.h
> +    void loadDynamicsPref(Preferences* pref);
```suggestion
    void loadDynamicsPref();
```
And move `#include "app/pref/preferences.h"` to the `dynamics_popup.cpp`

2023-08-17 22:03 UTC, dacap commented on src/app/ui/dynamics_popup.h
> +    void sharedSettings(bool state);
This is not used
```suggestion
```

2023-08-18 14:44 UTC, Gasparoken commented
Ready for review.

2023-08-18 14:45 UTC, Gasparoken commented on src/app/ui/context_bar.cpp
> +    m_popup.reset(new DynamicsPopup(this));
You're right. No needed. I added an `if (!m_popup.get())`

2023-08-18 18:11 UTC, Gasparoken commented
> The commit of this PR now looks a little strange ([815ffda](https://github.com/aseprite/aseprite/commit/815ffda1b0c0e2344a490cca86333fae105f74fb)), it looks like @martincapello is the author and you the committer, but I thought you was the author (?)

Incredible! I don't know how that is possible. I'll push again.

2023-08-18 18:21 UTC, Gasparoken commented
Done

2023-08-18 18:35 UTC, dacap commented
I'll merge it as it is, was able to test it a little, I don't like that checking the "Same in all tools" will set the properties of all tools. I'll make a TODO comment about this.

2023-08-18 18:35 UTC, merged