Fix in Save dialogs, current directory is not last visited (fix #3996)
aseprite/aseprite pull request #4025
Opened 2023-08-30 19:47 UTC by Gasparoken

This regression was added in 1.3rc5.
Every time you wanted to save a new sprite the dialog would start at the root path instead of the last used directory location.

fix #3996

2023-08-30 20:27 UTC, Gasparoken commented
This solution solves the problem, but I don't know the initial intention of the fix where the regression was inserted. So maybe there's something deeper.

2023-09-13 18:26 UTC, dacap requested changes
I was finally able to test this fix. Just a minor change in the code and you can change the commit message to something like this:
```
Fix initial folder for File > Save with the last one visited (fix #3996)

Regression added in 056073b3f1a7d54cdf9a113110f50947b9b4d525 in the
custom file selector. Every time you saved a new sprite the dialog
would start at the root path (e.g. Desktop) instead of the last used
directory.
```

2023-09-13 18:26 UTC, dacap commented on src/app/ui/file_selector.cpp
> +    start_folder_path = get_current_dir_for_file_selector();
We can use `get_initial_path_to_select_filename()` to get the initial path+filename path, use the following code which has the same effect as the proposed fix:
```suggestion
  std::string start_folder_path =
    base::get_file_path(
      get_initial_path_to_select_filename(initialPath));
```

2023-09-13 18:52 UTC, Gasparoken commented
Ready for merge

2023-09-14 15:31 UTC, merged