Allow selecting how the user wants to see the opacity/alpha values
aseprite/aseprite pull request #4262
Opened 2024-01-08 19:59 UTC by martincapello

This PR introduces a new preference for displaying and entering opacity/alpha values.
With this changes the user can select the range of values used which are:
1. 0%-100% 
2. 0-255

Fix #1544

2024-01-12 17:09 UTC, dacap requested changes
So far it looks great 👍 I wasn't able to test this yet, but I just made some minor comments.

2024-01-12 17:09 UTC, dacap commented on data/strings/en.ini
> +percentage_cs = 0%-100%
The `_cs` suffix means "color space", which I think it's not the case for these strings.

2024-01-12 17:09 UTC, dacap commented on data/pref.xml
> +      <value id="EIGHT_BIT" value="1" />
This is a minor thing, but I'd switch the values: PERCENTAGE=1 and EIGHT_BIT (or raw) =0 (these values don't care too much, but sometimes in scripts we have to use them as they are, and we can see `0` as the "most basic representation" (raw bytes) and then any following number as special representations).

```suggestion
      <value id="EIGHT_BIT" value="0" />
      <value id="PERCENTAGE" value="1" />
```

2024-01-31 15:53 UTC, dacap requested changes
Some changes required.

Probably we could connect preference changes from the same `AlphaSlider` ctor (e.g. so they are controlled automatically e.g. on ColorPopup/ColorSliders):

![alpha-slider](https://github.com/aseprite/aseprite/assets/39654/08948751-66d9-472e-9fac-89ebec66689c)

2024-01-31 15:53 UTC, dacap commented on src/app/ui/alpha_entry.cpp
> +AlphaEntry::AlphaEntry(AlphaSlider::Type type)
I think this class has too much in common with IntEntry, isn't a way to derive IntEntry and avoid duplicating code?

2024-01-31 15:53 UTC, dacap commented on src/app/ui/alpha_slider.cpp
> +bool AlphaSlider::onProcessMessage(ui::Message* msg)
Some messages handling are similar to the original `Slider::onProcessMessage`, wouldn't be possible to expand Slider (e.g. with some virtual methods that can be override in AlphaSlider) to customize the behavior and avoid duplicating code?

2024-01-31 15:53 UTC, dacap commented on src/app/ui/alpha_slider.h
> +
Minor formatting changes can be made (+ moving AlphaSlider ctor to the .cpp file):
```suggestion
class AlphaSlider : public ui::Slider,
                    ui::SliderDelegate
{
public:
  enum Type { ALPHA, OPACITY };

  AlphaSlider(int value, Type type);
      
  void getSliderThemeInfo(int* min, int* max, int* value) const override;
  void updateValue(int value);
  
  app::gen::AlphaRange getAlphaRange() const {
    return (m_type == ALPHA ? Preferences::instance().range.alpha()
                            : Preferences::instance().range.opacity());
  }

protected:
  bool onProcessMessage(ui::Message* msg) override;

private:
  // ui::SliderDelegate impl
  std::string onGetTextFromValue(int value) override;
  int onGetValueFromText(const std::string& text) override;

  Type m_type;
};

```
Generally we want to put data members as the last items in the class definition (doesn't modify the structure of the class, but just for readability we want to put all member functions before data).

2024-01-31 15:53 UTC, dacap commented on src/app/ui/alpha_slider.cpp
> +  switch(getAlphaRange()) {
```suggestion
  switch (getAlphaRange()) {
```

2024-02-06 14:40 UTC, martincapello commented
> Probably we could connect preference changes from the same AlphaSlider ctor (e.g. so they are controlled automatically e.g. on ColorPopup/ColorSliders):

Actually it seems that it is not that simple. The AlphaSlider doesn't contain the AlphaEntry, is the other way around. So I cannot update an entry from an AlphaSlider. In addition to this, the ColorSliders use a ColorEntry instance, which doesn't extend AlphaEntry at all. The ColorSliders just use the AlphaSlider, then to update the ColorEntry when the preference is changed, we should:
1. Connect to the preference change from the AlphaSlider ctor, then fire another signal from AlphaSlider to indicate this.
2. Connect to the AlphaSlider signal from the ColorSliders to be able to update the ColorEntry.

This actually doesn't seem practical...it actually involves more coding than connecting the ColorSliders directly to the preference change.

Maybe I'm missing something and there is an alternative that I don't see, please let me know if you have something else in mind.

2024-02-06 19:08 UTC, dacap commented
> Actually it seems that it is not that simple.

Yeah, it's more complex from what I thought, we can leave this as it is because the change of the preference is not something quite common (probably done just one time and then never more).

I'll test the PR a little more and then merge it as it looks great so far 👍

2024-02-06 19:30 UTC, dacap commented
It looks like dragging with the right mouse button on an AlphaSlider configured with % is not working correctly:

https://github.com/aseprite/aseprite/assets/39654/6ece43d0-6358-4e84-9d6f-4f279874064d

2024-02-07 16:39 UTC, martincapello commented
> It looks like dragging with the right mouse button on an AlphaSlider configured with % is not working correctly:

I just pushed some changes to slider.cpp to fix this.

2024-02-08 18:38 UTC, merged

2024-02-08 18:38 UTC, dacap commented
Nice work! I've just merged it 👍