Fix tabs ID handling in scripting engine
aseprite/aseprite pull request #4277
Opened 2024-01-19 20:07 UTC by martincapello

Fix #4268

2024-01-23 12:11 UTC, Gasparoken approved these changes
LGTM.

2024-02-06 19:48 UTC, dacap requested changes
Minor changes.

2024-02-06 19:48 UTC, dacap commented on src/app/script/tabs_widget.cpp
> +Tab* Tabs::addTab(std::string id, std::string text)
```suggestion
Tab* Tabs::addTab(const std::string& id, const std::string& text)
```

2024-02-06 19:48 UTC, dacap commented on src/app/script/tabs_widget.h
> +  Tab* addTab(std::string id, std::string text);
```suggestion
  Tab* addTab(const std::string& id, const std::string& text);
```

2024-02-06 19:48 UTC, dacap commented on src/app/script/tabs_widget.cpp
> +        bool isSelectedTab = TAB_CONTENT_ID(tab->id()) == tabContent->id();
```suggestion
        bool isSelectedTab = (TAB_CONTENT_ID(tab->id()) == tabContent->id());
```

2024-02-08 13:55 UTC, merged