Use right click action with shading ink (fix #4520)
aseprite/aseprite pull request #4615
Opened 2024-08-26 22:17 UTC by Liebranca

Save the number of selected entries in `PaletteView` so that `ActiveToolManager` can access this value in `isToolAffectedByRightClickMode`.

If the number of colors that were last manually selected is less than two, allow the configured right click action during shading mode.

This value ignores reversal; it will only change uppon a new selection, be it a single color or another range.

2024-08-27 12:10 UTC, dacap requested changes
Hi @Liebranca, check the review comments and the actions: https://github.com/aseprite/aseprite/actions/runs/10568125733 when compiling with `ENABLE_UI=OFF` is failing (there is no `ColorBar` when compiling without UI).

2024-08-27 12:10 UTC, dacap commented on src/app/tools/active_tool.cpp
> +      shadingMode = false;
Be aware that the user can change the selected shades from the `ContextBar` itself:

![image](https://github.com/user-attachments/assets/01f25c08-7615-423e-b51c-e9823587fce7)

The information of the active shades can be accessed through the `ContextBar::getShade()` member function.

2024-08-28 05:27 UTC, Liebranca commented
Hi @dacap, added a bit of logic to my scripts to automatically compile with and without UI, so now I should catch this early.

Discarded the initial unorthodox workaround for the more straightforward approach through `ContextBar`, and placed the new check behind a preprocessor switch (else left as it was).

However, it seems that excluding some of these functions themselves from compilation altogether via such a switch may be more appropriate, since they're only needed by UI elements in the first place. What do you think?

2024-08-28 17:50 UTC, dacap commented
> it seems that excluding some of these functions themselves from compilation altogether via such a switch may be more appropriate, since they're only needed by UI elements in the first place. What do you think?

Yeah, there are some work already done in `src/app/CMakeLists.txt` to only include UI-dependent files when `ENABLE_UI` is true, e.g.:

https://github.com/aseprite/aseprite/blob/e87f6df72b03bfc5c17bc3e53dd88145e1b0f368/src/app/CMakeLists.txt#L252

But it's like a "refactor in progress". We have the inverse case too, i.e. commands that are included only when `ENABLE_UI` is on, but should be always available (like `InvertMask`, etc.):

https://github.com/aseprite/aseprite/blob/e87f6df72b03bfc5c17bc3e53dd88145e1b0f368/src/app/commands/commands_list.h#L64

The case of the `ActiveToolManager` is a little complex because it's used in the scripting API too. Probably for simple things, like just storing the active tool, without even calling functions related to UI events (newToolSelectedInToolBar, regularTipProximity, etc.). I don't think it's worth refactoring at the moment.

Even more, this `ENABLE_UI` was created to fix #1279 but never really used (and now we are compiling the full version in GitHub CI), so I'm not sure if we should keep the flag or just remove it and simplify the maintenance. I'll create a new issue about this.

2024-08-28 17:52 UTC, dacap commented on src/app/tools/active_tool.cpp
> +#include "app/app.h"
Oh a little thing I missed at a glance is that we generally include the header file related to the `.cpp` as the first header file (after the `config.h` thing) and then all other files, e.g. to check that `"app/tools/active_tool.h"` includes everything it needs.

2024-08-29 13:45 UTC, merged