Add diagonal symmetry
aseprite/aseprite pull request #4669
Opened 2024-09-18 16:12 UTC by Gasparoken

Added symmetry UI buttons, 45 and -45 degrees axis. Now are possible activate all four symmetries, both diagonal symmetries, individual diagonal symmetry, and the old horizontal/vertical combinations.

Also, this fix implements the flip of image brushes itself.

fix https://github.com/aseprite/aseprite/issues/1171

2024-09-18 16:14 UTC, Gasparoken commented
Transcript of @dacap's comment (https://github.com/aseprite/aseprite/pull/4666#issuecomment-2358576633)
> ...I see that there are a lot of bugs with the current symmetry impl (e.g. enabling Dynamics creates non-symmetrical pixels). The solution would be to move the symmetry part into other part of the ToolLoop pipeline (instead of copying strokes, copying pixels), but that will be for another issue (I'll create a new one soon, I don't know if it already exists).

2024-09-18 18:22 UTC, Gasparoken commented
I will add some tests

2024-09-19 17:57 UTC, Gasparoken commented
@dacap Ready for review.

Some comments:
1. Simple diagonal symmetry axis handlers point to a virtual center (instead of being placed at the ends of the axis).
2. The image brush in a 'Pattern aligned to...' mode doesn't reflect the pattern, only its bounds.
3. Bugs in Tiled Mode when trying to paint outside the central portion of the canvas.

Anyway, I think it's a good start!

2024-09-20 20:52 UTC, martincapello reviewed
It looks good! I've tested it and feels good too! I've made some comments because I think we can avoid copying some images.

2024-09-20 20:52 UTC, martincapello commented on src/doc/brush.cpp
> +          m_symmetryImages[index].reset(Image::createCopy(tempImage.get()));
I think we can set the tempImage directly and avoid the extra copy:
```c++
m_symmetryImages[index].reset(tempImage.release());
```

2024-09-20 20:52 UTC, martincapello commented on src/doc/brush.cpp
> +          m_symmetryMasks[index].reset(Image::createCopy(tempImage.get()));
Same here.

2024-09-20 20:52 UTC, martincapello commented on src/doc/brush.cpp
> +          m_symmetryImages[index].reset(Image::createCopy(tempImage.get()));
Same here.

2024-09-20 20:52 UTC, martincapello commented on src/doc/brush.cpp
> +          m_symmetryMasks[index].reset(Image::createCopy(tempImage.get()));
Same here.

2024-09-20 20:52 UTC, martincapello commented on src/doc/brush.cpp
> +          m_symmetryImages[index].reset(Image::createCopy(tempImage.get()));
Same here.

2024-09-20 20:52 UTC, martincapello commented on src/doc/brush.cpp
> +          m_symmetryMasks[index].reset(Image::createCopy(tempImage.get()));
Same here.

2024-09-20 20:52 UTC, martincapello commented on src/doc/brush.cpp
> +        m_symmetryImages[index].reset(Image::createCopy(tempImage.get()));
Same here.

2024-09-20 20:52 UTC, martincapello commented on src/doc/brush.cpp
> +          m_symmetryMasks[index].reset(Image::createCopy(tempImage.get()));
Same here.

2024-09-23 13:08 UTC, Gasparoken commented
> It looks good! I've tested it and feels good too! I've made some comments because I think we can avoid copying some images.

Thanks! Nice addition!

2024-10-24 13:30 UTC, dacap requested changes
It works great :partying_face:

I've made some minor comments to check. One thing we'd like to test/improve after this is merged, is to avoid as many `resetSymmetries()` as possible when dynamics are enabled. But probably for other PR.

2024-10-24 13:30 UTC, dacap commented on src/doc/brush.cpp
> +  if (index <= 0 || index > 7)
```suggestion
  if (index <= SymmetryIndex::ORIGINAL || index > SymmetryIndex::ELEMENTS)
```

2024-10-24 13:30 UTC, dacap commented on src/doc/brush.cpp
> +void Brush::resetSymmetries()
Something I don't quite like is the fact that these vectors are always resized in `resetSymmetries()`, even when they are never used. I think `resetSymmetries()` could do nothing if `m_symmetryImages` is empty, and we could add a new private member function `reserveSymmetries()` that does what `resetSymmetries` does now and that is called from `getSymmetryImage/Mask` when needed.

2024-10-24 13:30 UTC, dacap commented on tests/scripts/tools.lua
> +	             0, 0, 0, 0, 0, 0, 0, 0 })
Remove this change in indentation in the whole file, try to use whitespaces instead of tabs.

2024-10-25 15:10 UTC, Gasparoken commented on src/app/tools/ink_processing.h
> -  BrushPattern m_patternAlign;
Thanks! This will be a great improvement. Also, there will be no need to cache `m_symmetryIndex`.

2024-10-31 15:29 UTC, dacap requested changes
Still some changes weren't merged. Please commit amending the last commit in this PR.

I'll see how to merge this, I'll try to squash as little commits as possible, but if I cannot I'll squash the whole PR.

2024-10-31 15:29 UTC, dacap commented on src/app/tools/ink_processing.h
> +    const int brushH(brushHeight());
```suggestion
    const int brushH = brushHeight();
```

2024-10-31 15:29 UTC, dacap commented on src/app/tools/ink_processing.h
> +    const int brushW(brushWidth());
```suggestion
    const int brushW = brushWidth();
```

2024-10-31 15:29 UTC, dacap commented on src/app/tools/ink_processing.h
> +  }
Remove `const` in return type:
```suggestion
  inline int brushWidth() const {
    return m_isBoundsRotated ? m_height : m_width;
  }
  inline int brushHeight() const {
    return m_isBoundsRotated ? m_width : m_height;
  }
```

2024-10-31 15:29 UTC, dacap commented on src/doc/brush.cpp
> +        }
I think this wasn't yet fixed.

2024-10-31 15:29 UTC, dacap commented on src/doc/brush.cpp
> +    switch (index) {
This wasn't added.

2024-10-31 15:29 UTC, dacap commented on src/doc/brush.cpp
> +  if (index <= 0 || index > 7)
This wasn't added?

2024-10-31 15:29 UTC, dacap commented on src/app/tools/point_shapes.h
> +  std::array<std::shared_ptr<CompressedImage>, 8> m_compressedImages;
Change the 8 with the `BrushIndex::ELEMENTS` constant:
```suggestion
  std::array<std::shared_ptr<CompressedImage>, int(BrushIndex::ELEMENTS)> m_compressedImages;
```

2024-10-31 15:29 UTC, dacap commented on tests/scripts/tools.lua
> +	             0, 0, 0, 0, 0, 0, 0, 0 })
Try to avoid tabs or use tabs=8 spaces.

2024-10-31 18:12 UTC, Gasparoken commented
@dacap if you wish, I can make a new set of ordered commits that include all the changes to get a cleaner PR.

2024-11-04 18:32 UTC, merged

2024-11-04 18:33 UTC, dacap commented
Great! 🚀 just merged, there is a little minor thing with the buttons but I'll create another issue for that, is something minor to see later.