Enable and improve beforesitechange event (fix #4785)
aseprite/aseprite pull request #4820
Opened 2024-11-23 13:56 UTC by ckaiser

Fixes #4785, should cover the buggy cases. I also confirmed it works with normal closing of the program.

Demonstration with @dacap's test script (Which btw had a typo, `app.image` was working properly, it was the Lua code with an extra capital letter 😅)

https://github.com/user-attachments/assets/212c2aa2-d479-4dd0-a7b6-eca3d8968754

2024-11-25 23:37 UTC, dacap commented
> Which btw had a typo, `app.image` was working properly, it was the Lua code with an extra capital letter 😅

Oh sorry about that, I'll try to test and take a look to this PR tomorrow :+1:

2024-12-10 15:06 UTC, dacap requested changes
> I'll try to test and take a look to this PR tomorrow

OK, tomorrow sometimes is 2 weeks :sweat_smile:

I didn't fully tested yet, but some small changes are required to make it work for some cases.

2024-12-18 15:05 UTC, dacap commented
Based on your rebase @ckaiser, I've rebased with clang-format on each commit: https://github.com/dacap/aseprite/tree/fix/beforesitechange (you can continue from there).

I noticed this issue when closing a doc (the line with ERR):

![image](https://github.com/user-attachments/assets/6750ccf0-6cdc-4413-9db9-1644efffe848)

Probably not too much to worry about :thinking:

2024-12-18 18:45 UTC, ckaiser commented
Hm, strange, I can't reproduce that. I may have changed the script thing too much? This is my version: [dacap-test.zip](https://github.com/user-attachments/files/18187531/dacap-test.zip) - it's basically the same but with a separator so there shouldn't really be any difference.

2024-12-18 21:22 UTC, dacap commented
> Hm, strange, I can't reproduce that. I may have changed the script thing too much?

Same script here. But tested a little more and I was able to reproduce the exact steps. For example, this works correctly:

1. Create a new sprite
2. Close it

But the following generates this extra ERR before site change event:

1. Create a new sprite
2. *Close the Home tab*
3. Close the sprite

And if you keep the Home tab closed, just creating a new sprite and closing it as in the first example, will start printing the ERR line.

2025-01-02 21:05 UTC, merged